### ISSUE TITLE
uPlot line charts

### ISSUE THREAD

**Issue by leeoniya** [EnviDat/gcnet-frontend#1]
hey @DomDomHaas 

since my simple suggestion to try [uPlot](https://github.com/leeoniya/uPlot) was unceremoniously deleted from https://github.com/amcharts/amcharts4/issues/2395, here's my benchmark of amChart's performance compared to a dozen other charting libraries:

https://github.com/leeoniya/uPlot#performance

there are users with hundreds of sensor uPlot instances per page [1][2] with no performance issues.

cheers!

[1] https://github.com/leeoniya/uPlot/issues/95#issue-553196323
[2] https://github.com/leeoniya/uPlot/issues/36#issue-513489222

**Comment by DomDomHaas** [comment]
Hey thanks so much. Very important :)

How's the learning curve for uPlot?

A bit fishy that they deleted it xD

**Comment by DomDomHaas** [comment]
Aha and how did you do the benchmarks? :)

**Comment by leeoniya** [comment]
> How's the learning curve for uPlot?

for me it's 0 :D, but the API is quite small, so hopefully not much of a curve.

the docs are a work in progress but the API is fully documented in

https://github.com/leeoniya/uPlot/blob/master/dist/uPlot.esm.d.ts

these demos cover 95% of the API:

https://leeoniya.github.io/uPlot/demos/index.html

> A bit fishy that they deleted it xD

they have a slow product to sell, so it probably makes sense.

> Aha and how did you do the benchmarks? :)

they all render a line chart with 3 series, containing 166k datapoints total.

the code for each framework is here:

https://github.com/leeoniya/uPlot/tree/master/bench

you can click on each framework in the perf table to open the live bench for each.

**Comment by leeoniya** [comment]
if you end up trying uPlot, i'd love to see some before/after perf numbers 🤣

**Comment by martynasma** [comment]
@leeoniya seriously? Is this cool to use GitHub issues that are meant for reporting bugs to promote other stuff, and taking offense when such posts are getting removed?
